# Generated by Django 4.1.1 on 2022-09-29 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_imgage',
            new_name='post_image',
        ),
    ]
