# Generated by Django 4.1.1 on 2022-09-29 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_post_imgage_post_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_dat',
            new_name='post_date',
        ),
    ]
