# Generated by Django 4.1.1 on 2022-10-03 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votes',
            old_name='down_vote_by',
            new_name='diss_liked_by',
        ),
        migrations.RenameField(
            model_name='votes',
            old_name='up_vote_by',
            new_name='liked_by',
        ),
    ]
