# Generated by Django 4.1.1 on 2022-10-04 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='comments',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='comment.comment'),
            preserve_default=False,
        ),
    ]
